"""Initial migration

Revision ID: c2fe888b7472
Revises: 
Create Date: 2025-01-26 23:54:27.871563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2fe888b7472'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('track_ids', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlists_id'), 'playlists', ['id'], unique=False)
    op.create_table('album_compatibilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_1', sa.Integer(), nullable=False),
    sa.Column('user_id_2', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('compatibility_score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ),
    sa.ForeignKeyConstraint(['user_id_1'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id_2'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_album_compatibilities_id'), 'album_compatibilities', ['id'], unique=False)
    op.create_table('artist_compatibilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_1', sa.Integer(), nullable=False),
    sa.Column('user_id_2', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('compatibility_score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['user_id_1'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id_2'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artist_compatibilities_id'), 'artist_compatibilities', ['id'], unique=False)
    op.create_table('compatibilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_1', sa.Integer(), nullable=False),
    sa.Column('user_id_2', sa.Integer(), nullable=False),
    sa.Column('compatibility_score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id_1'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id_2'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compatibilities_id'), 'compatibilities', ['id'], unique=False)
    op.create_table('listening_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('album', sa.Integer(), nullable=False),
    sa.Column('play_count', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['album'], ['albums.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listening_histories_id'), 'listening_histories', ['id'], unique=False)
    op.create_table('track_compatibilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_1', sa.Integer(), nullable=False),
    sa.Column('user_id_2', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('compatibility_score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.ForeignKeyConstraint(['user_id_1'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id_2'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_track_compatibilities_id'), 'track_compatibilities', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_track_compatibilities_id'), table_name='track_compatibilities')
    op.drop_table('track_compatibilities')
    op.drop_index(op.f('ix_listening_histories_id'), table_name='listening_histories')
    op.drop_table('listening_histories')
    op.drop_index(op.f('ix_compatibilities_id'), table_name='compatibilities')
    op.drop_table('compatibilities')
    op.drop_index(op.f('ix_artist_compatibilities_id'), table_name='artist_compatibilities')
    op.drop_table('artist_compatibilities')
    op.drop_index(op.f('ix_album_compatibilities_id'), table_name='album_compatibilities')
    op.drop_table('album_compatibilities')
    op.drop_index(op.f('ix_playlists_id'), table_name='playlists')
    op.drop_table('playlists')
    # ### end Alembic commands ###
