"""added aoty_ratings_Count

Revision ID: a98360898b72
Revises: d1ac2d4f2423
Create Date: 2025-02-17 17:44:07.112215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a98360898b72'
down_revision: Union[str, None] = 'd1ac2d4f2423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('aoty_rating_count', sa.Integer(), nullable=True))
    op.add_column('artists', sa.Column('aoty_rating_count', sa.Integer(), nullable=True))
    op.add_column('tracks', sa.Column('aoty_rating_count', sa.Integer(), nullable=True))
    op.drop_column('tracks', 'loudness')
    op.drop_column('tracks', 'valence')
    op.drop_column('tracks', 'instrumentalness')
    op.drop_column('tracks', 'preview_url')
    op.drop_column('tracks', 'energy')
    op.drop_column('tracks', 'danceability')
    op.drop_column('tracks', 'acousticness')
    op.drop_column('tracks', 'speechiness')
    op.drop_column('tracks', 'tempo')
    op.drop_column('user_albums', 'source')
    op.drop_column('user_artists', 'source')
    op.drop_column('user_tracks', 'source')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tracks', sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user_artists', sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user_albums', sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('tracks', sa.Column('tempo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('tracks', sa.Column('speechiness', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('tracks', sa.Column('acousticness', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('tracks', sa.Column('danceability', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('tracks', sa.Column('energy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('tracks', sa.Column('preview_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tracks', sa.Column('instrumentalness', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('tracks', sa.Column('valence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('tracks', sa.Column('loudness', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('tracks', 'aoty_rating_count')
    op.drop_column('artists', 'aoty_rating_count')
    op.drop_column('albums', 'aoty_rating_count')
    # ### end Alembic commands ###
